### ISSUE TITLE
Change how to connect to specified device.

### ISSUE THREAD

**Issue by erwintel** [Wikilicious/pygmc#65]
Making a connection to desired device feels unpythonic `gc = pygmc.GMC320.connect(port='/dev/ttyUSB0')`  
Why not `gc = pygmc.GMC320(port='/dev/ttyUSB0')` 
Has the added benefit of coding in usb connection quirks on a per-device basis.

**Comment by Wikilicious** [comment]
Ugh, I'm not a fan of how I set it up either... I think I need to rearchitect the connection component.

**Comment by Wikilicious** [comment]
I'm now rethinking the whole paradigm. It looks like a lot more work than I thought.

**Comment by Wikilicious** [comment]
Ok, adding a patch.
