### ISSUE TITLE
GMC-800 Software Issues

### ISSUE THREAD

**Issue by Wikilicious** [Wikilicious/pygmc#92]
Looks like there are un-documented and mis-documented features... https://www.gqelectronicsllc.com/forum/topic.asp?TOPIC_ID=10394

Let's wait for reply then make the changes here.

**Comment by Wikilicious** [comment]
Ugh... no meaningful updates.

**Comment by Wikilicious** [comment]
Still nothing.  
I ended up ordering a GMC-800 to figure it out myself.  
Perhaps to redeem myself for a shameful purchase of a "FNIRSI GC-01" I wanted to expand pygmc support beyond GQ...  

My instinct is to raise `UnsupportedError` Because specifications are specifications... documenting them then not supporting them is an error... that error should reflect the source. 

The issue was originally discovered by @ullix (https://github.com/ullix)

**Comment by ullix** [comment]
Good! Once you hold your device in hand, I encourage you to do some testing as discussed here:
https://sourceforge.net/p/geigerlog/discussion/devel/
GMC-800 should by now be fully supported by GeigerLog

**Comment by Wikilicious** [comment]
`gc.get_cpm()` wasn't working... 
I clear out the buffers then issue the cmd `b'<GETCPM>>'` then wait a sec then read the entire buffer...
Guess what I see...
`b'\x00\x00\x00\x11'` 
4 bytes not 2. 

It's listed as RFC1201 in https://www.gqelectronicsllc.com/GMC-800UserGuide.pdf
But uses RFC1801 byte size and has GETCPS... It's closer to RFC1801

**Comment by Wikilicious** [comment]
Copy-pasting for a record... from https://www.gqelectronicsllc.com/forum/topic.asp?TOPIC_ID=10394 Reply#2

```
Most of these are not used like the old calibration and alarm. And the save threshold also are not used anymore. And disregard the numbering.

POWERONOFF,
AlarmOnOff,
SpeakerOnOff,
GRAPHIC_UNIT,
BackLightTimeoutSeconds,
IdleTitleDisplayMode,
AlarmCPMValueHiByte, //6
AlarmCPMValueLoByte,
CalibrationCPMHiByte_0,
CalibrationCPMLoByte_0,
CalibrationuSvUcByte3_0,
CalibrationuSvUcByte2_0, //11
CalibrationuSvUcByte1_0,
CalibrationuSvUcByte0_0,
CalibrationCPMHiByte_1,
CalibrationCPMLoByte_1, //15
CalibrationuSvUcByte3_1,
CalibrationuSvUcByte2_1,
CalibrationuSvUcByte1_1,
CalibrationuSvUcByte0_1,
CalibrationCPMHiByte_2, //20
CalibrationCPMLoByte_2,
CalibrationuSvUcByte3_2,
CalibrationuSvUcByte2_2,
CalibrationuSvUcByte1_2,
CalibrationuSvUcByte0_2, //25
IdleDisplayMode,
AlarmValueuSvByte3,
AlarmValueuSvByte2,
AlarmValueuSvByte1,
AlarmValueuSvByte0, //30
AlarmType,
SaveDataType,
SwivelDisplay,
ZoomByte3,
ZoomByte2, //35
ZoomByte1,
ZoomByte0,
SPI_DataSaveAddress2,
SPI_DataSaveAddress1,
SPI_DataSaveAddress0, //40
SPI_DataReadAddress2,
SPI_DataReadAddress1,
SPI_DataReadAddress0,
nPowerSavingMode,
nSensitivityMode, //45
nCOUNTER_DELAY_HiByte,
nCOUNTER_DELAY_LoByte,
nDisplayContrast,
MAX_CPM_HIBYTE,
MAX_CPM_LOBYTE, //50
nSensitivityAutoModeThreshold,
LARGE_FONT_UNIT,
nLCDBackLightLevel,
nReverseDisplayMode,
nMotionDetect, //55
bBatteryType,
nBaudRate,
nCPMSpeakerOnOffCalib,
GRAPHIC_MODE,
nLEDOnOff,
nHCPMCAL,
nSaveThresholdValueuSv_m_nCPM_HIBYTE,
nSaveThresholdValueuSv_m_nCPM_LOBYTE,
nSaveThresholdMode,
nSaveThresholdValue3,
nSaveThresholdValue2,
nSaveThresholdValue1,
nSaveThresholdValue0,
FAST_ESTIMATE_TIME,
RTC_OFFSET,
ALARM_VOLUME,
TUBE_VOLTAGE,

CALIBRATION_CPM_MSB_0,
CALIBRATION_CPM_LSB_5 = CALIBRATION_CPM_MSB_0 + 23,
CALIBRATION_USV0_BYTE3,
CALIBRATION_USV5_BYTE0 = CALIBRATION_USV0_BYTE3 + 23,

CLICK_SOUND,
SPEAKER_VOLUME,
VIBRATION,
DOSIMETER_UNIT,

ALARM_CPM_BYTE3,
ALARM_CPM_BYTE2,
ALARM_CPM_BYTE1,
ALARM_CPM_BYTE0,

THEME,
DARK_THEME_COLOR_BYTE1,
DARK_THEME_COLOR_BYTE0,
```


Yet...
clear buffers, issue cmd `b"<GETCFG>>"` wait 5 sec then read entire buffer...
```b'\x00\x00\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\xff\xff\xff\xff\xff\x01\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\xff\xff\xff\xff\xff\xff\xff\x00\n\xff\xff\xff\xff\xff\x00\x01\xff\xff\xff\xff\xff\xff\xff\xff\x03\xff\x0f,\x00\x00\x06\x02\x00\x00<\x14\x00\x00x(\x00\x01,d\x00\x02X\xc8\x00\x04\xb1\x90A \x00\x00B\xc8\x00\x00CH\x00\x00C\xfa\x00\x00Dz\x00\x00D\xfa\x00\x00\x00\x00\x01\x01\x00\x00\x00d\x00\xff\x06\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'```

The calibration config is all `\xff`

**Comment by Wikilicious** [comment]
https://www.gqelectronicsllc.com/forum/topic.asp?TOPIC_ID=10394 Reply#15
It's unclear if only GMC800 is impacted or if ALL RFC1201 devices are... 

Instinct is to create a dummy spec `RFC404` (a nod to 404-not-found) and assign it to GMC-800.
